spring.application.name=tcg-server
server.address=0.0.0.0
server.port=8080
spring.web.resources.static-locations=classpath:/views/
spring.mvc.async.request-timeout=30000

app.cors.allowed-origins=http://localhost:4200

firebase.database-url=https://online-tcg-arasesp-default-rtdb.europe-west1.firebasedatabase.app/
firebase.service-account-path=${FIREBASE_SERVICE_ACCOUNT_PATH:classpath:firebase/service-account.json}

cloudflare.tunnel.enabled=true
cloudflare.tunnel.command=C:/Users/Alejandro Rasero/AppData/Local/Microsoft/WinGet/Packages/Cloudflare.cloudflared_Microsoft.Winget.Source_8wekyb3d8bbwe/cloudflared.exe
cloudflare.tunnel.local-url=http://localhost:${server.port}
cloudflare.tunnel.firebase-path=config/backend
